var InBack = function() { return "easeInBack"; }
function OutBack() { return "easeOutBack"; }
function InOutBack() { return "easeInOutBack"; }
function InBounce() { return "easeInBounce"; }
function OutBounce() { return "easeOutBounce"; }
function InOutBounce() { return "easeInOutBounce"; }
function InCirc() { return "easeInCirc"; }
function OutCirc() { return "easeOutCirc"; }
function InOutCirc() { return "easeInOutCirc"; }
function InCubic() { return "easeInCubic"; }
function OutCubic() { return "easeOutCubic"; }
function InOutCubic() { return "easeInOutCubic"; }
function InElastic() { return "easeInElastic"; }
function OutElastic() { return "easeOutElastic"; }
function InOutElastic() { return "easeInOutElastic"; }
function InExpo() { return "easeInExpo"; }
function OutExpo() { return "easeOutExpo"; }
function InOutExpo() { return "easeInOutExpo"; }
function InQuad() { return "easeInQuad"; }
function OutQuad() { return "easeOutQuad"; }
function InOutQuad() { return "easeInOutQuad"; }
function InQuart() { return "easeInQuart"; }
function OutQuart() { return "easeOutQuart"; }
function InOutQuart() { return "easeInOutQuart"; }
function InQuint() { return "easeInQuint"; }
function OutQuint() { return "easeOutQuint"; }
function InOutQuint() { return "easeInOutQuint"; }
function InSine() { return "easeInSine"; }
function OutSine() { return "easeOutSine"; }
function InOutSine() { return "easeInOutSine"; }
function Linear() { return "linear"; }